/**
 * metamask.js  —  MetaMask + ethers.js wallet connection
 *
 * Place this file at:  static/js/metamask.js
 *
 * Include in cast_vote.html (and any page that needs wallet connection):
 *   <script src="https://cdnjs.cloudflare.com/ajax/libs/ethers/6.7.1/ethers.umd.min.js"></script>
 *   <script src="{{ url_for('static', filename='js/metamask.js') }}"></script>
 *
 * The script:
 *   1. Shows a "Connect MetaMask" button if window.ethereum is available
 *   2. On connect, reads wallet address and displays it
 *   3. Adds the wallet address to the vote form as a hidden field
 *   4. Signs a message (voter attestation) before submission
 *   5. Displays live tx status updates after the Flask backend submits
 */

(function () {
    'use strict';

    // ── ABI subset — only the functions we call from the browser ─────
    // Full ABI is in ElectionVoting_ABI.json (generated by Hardhat)
    const VOTE_ABI = [
        "event VoteCast(uint256 indexed voterId, string voterName, uint256 indexed nominationId, string role, uint256 timestamp)",
        "function hasVoted(uint256 voterId) view returns (bool)",
        "function getTotalVotes() view returns (uint256)",
        "function electionActive() view returns (bool)",
    ];

    // Read contract address from the page (injected by Flask template)
    const CONTRACT_ADDRESS = window.ELECTION_CONTRACT_ADDRESS || null;

    let provider = null;
    let signer   = null;
    let contract = null;
    let walletAddress = null;

    // ── DOM helpers ──────────────────────────────────────────────────

    function getOrCreate(id, tag = 'div') {
        let el = document.getElementById(id);
        if (!el) {
            el = document.createElement(tag);
            el.id = id;
        }
        return el;
    }

    function showStatus(msg, type = 'info') {
        const colors = { info: '#3498db', success: '#27ae60', error: '#e74c3c', warn: '#f39c12' };
        const box = getOrCreate('mm-status-box');
        box.style.cssText = `
            padding: 10px 16px;
            border-radius: 8px;
            background: ${colors[type]}20;
            border: 1px solid ${colors[type]};
            color: ${colors[type]};
            margin: 12px 0;
            font-size: 0.875rem;
            font-family: monospace;
        `;
        box.textContent = msg;
        return box;
    }

    // ── Inject the MetaMask widget into the page ─────────────────────

    function injectWidget() {
        const anchor = document.getElementById('metamask-widget-anchor')
            || document.querySelector('.blockchain-info-box')
            || document.querySelector('#voteForm');

        if (!anchor) return;

        const widget = document.createElement('div');
        widget.id = 'metamask-widget';
        widget.style.cssText = `
            background: #1a1a2e;
            border-radius: 12px;
            padding: 16px 20px;
            margin: 16px 0;
            color: #e8e8e8;
        `;
        widget.innerHTML = `
            <div style="display:flex;align-items:center;gap:10px;margin-bottom:12px;">
                <span style="font-size:1.4rem;">🦊</span>
                <span style="font-weight:700;font-size:1rem;">MetaMask Wallet</span>
                <span id="mm-network-badge" style="
                    font-size:0.7rem;padding:2px 8px;border-radius:20px;
                    background:#f39c12;color:#fff;margin-left:auto;
                ">Not Connected</span>
            </div>
            <div id="mm-wallet-info" style="display:none;">
                <div style="font-size:0.75rem;color:#aaa;">Connected Wallet</div>
                <div id="mm-address" style="font-family:monospace;font-size:0.82rem;
                    word-break:break-all;color:#2ecc71;margin-bottom:8px;"></div>
                <div style="font-size:0.75rem;color:#aaa;">Balance</div>
                <div id="mm-balance" style="font-family:monospace;font-size:0.82rem;color:#e8e8e8;"></div>
            </div>
            <button id="mm-connect-btn" style="
                background: #e8790a;
                color: #fff;
                border: none;
                padding: 8px 18px;
                border-radius: 8px;
                cursor: pointer;
                font-size: 0.875rem;
                font-weight: 600;
                margin-top: 8px;
                display: flex;
                align-items: center;
                gap: 6px;
            ">🦊 Connect MetaMask</button>
            <div id="mm-sign-section" style="display:none;margin-top:12px;">
                <button id="mm-sign-btn" style="
                    background:#27ae60;color:#fff;border:none;
                    padding:8px 18px;border-radius:8px;cursor:pointer;
                    font-size:0.875rem;font-weight:600;
                ">✍️ Sign Vote Attestation</button>
                <div id="mm-signature-display" style="display:none;margin-top:8px;
                    font-size:0.72rem;font-family:monospace;color:#aaa;word-break:break-all;"></div>
            </div>
            <div id="mm-status-container" style="margin-top:8px;"></div>
        `;

        anchor.insertAdjacentElement('beforebegin', widget);
        bindEvents();
    }

    // ── ethers.js connection ─────────────────────────────────────────

    async function connectMetaMask() {
        const btn = document.getElementById('mm-connect-btn');
        if (!window.ethereum) {
            alert('MetaMask is not installed.\n\nInstall it from https://metamask.io and refresh.');
            return;
        }

        try {
            btn.textContent = '⏳ Connecting…';
            btn.disabled = true;

            provider = new ethers.BrowserProvider(window.ethereum);
            await provider.send('eth_requestAccounts', []);
            signer = await provider.getSigner();
            walletAddress = await signer.getAddress();

            const network = await provider.getNetwork();
            const balance = await provider.getBalance(walletAddress);
            const ethBal  = ethers.formatEther(balance);

            // Update UI
            document.getElementById('mm-address').textContent = walletAddress;
            document.getElementById('mm-balance').textContent = parseFloat(ethBal).toFixed(4) + ' ETH';
            document.getElementById('mm-wallet-info').style.display = 'block';
            document.getElementById('mm-sign-section').style.display = 'block';
            btn.style.display = 'none';

            const badge = document.getElementById('mm-network-badge');
            badge.textContent = network.name + ' (' + network.chainId + ')';
            badge.style.background = '#27ae60';

            // Inject wallet address into the hidden form field
            let hiddenField = document.getElementById('wallet_address');
            if (!hiddenField) {
                hiddenField = document.createElement('input');
                hiddenField.type = 'hidden';
                hiddenField.id   = 'wallet_address';
                hiddenField.name = 'wallet_address';
                const form = document.getElementById('voteForm');
                if (form) form.appendChild(hiddenField);
            }
            hiddenField.value = walletAddress;

            // Connect to contract for read-only checks
            if (CONTRACT_ADDRESS && window.ethers) {
                try {
                    contract = new ethers.Contract(CONTRACT_ADDRESS, VOTE_ABI, provider);
                    const totalVotes = await contract.getTotalVotes();
                    const statusBox = showStatus(
                        `✅ Connected | ${totalVotes} votes on-chain | Wallet: ${walletAddress.slice(0, 10)}…`,
                        'success'
                    );
                    document.getElementById('mm-status-container').appendChild(statusBox);
                } catch (e) {
                    console.warn('Contract read failed (safe to ignore if no contract yet):', e.message);
                }
            } else {
                const statusBox = showStatus(`✅ Wallet connected: ${walletAddress.slice(0, 14)}…`, 'success');
                document.getElementById('mm-status-container').appendChild(statusBox);
            }

        } catch (err) {
            btn.textContent = '🦊 Connect MetaMask';
            btn.disabled = false;
            const statusBox = showStatus('❌ Connection failed: ' + err.message, 'error');
            document.getElementById('mm-status-container').appendChild(statusBox);
        }
    }

    async function signAttestation() {
        if (!signer) {
            alert('Connect MetaMask first.');
            return;
        }

        const signBtn = document.getElementById('mm-sign-btn');
        const sigDisplay = document.getElementById('mm-signature-display');

        try {
            signBtn.textContent = '⏳ Signing…';
            signBtn.disabled = true;

            const msg = [
                'I am casting my vote in the College Election System.',
                'Wallet: ' + walletAddress,
                'Timestamp: ' + new Date().toISOString(),
                'I confirm this vote is my own and I have not voted before.',
            ].join('\n');

            const signature = await signer.signMessage(msg);

            // Store signature as hidden field
            let sigField = document.getElementById('wallet_signature');
            if (!sigField) {
                sigField = document.createElement('input');
                sigField.type = 'hidden';
                sigField.id   = 'wallet_signature';
                sigField.name = 'wallet_signature';
                const form = document.getElementById('voteForm');
                if (form) form.appendChild(sigField);
            }
            sigField.value = signature;

            sigDisplay.style.display = 'block';
            sigDisplay.innerHTML = '✅ Signed: <span style="color:#2ecc71;">' + signature.slice(0, 40) + '…</span>';

            signBtn.textContent = '✅ Attestation Signed';
            signBtn.style.background = '#27ae60';

            // Enable the submit button
            const submitBtn = document.querySelector('#voteForm button[type="submit"]');
            if (submitBtn) {
                submitBtn.style.boxShadow = '0 0 0 3px #27ae6080';
            }

        } catch (err) {
            signBtn.textContent = '✍️ Sign Vote Attestation';
            signBtn.disabled = false;
            const statusBox = showStatus('❌ Signing failed: ' + err.message, 'error');
            document.getElementById('mm-status-container').appendChild(statusBox);
        }
    }

    // ── Listen for VoteCast events after form submit ──────────────────

    function watchForVoteEvent(voterId) {
        if (!contract) return;
        try {
            contract.on('VoteCast', (vid, voterName, nomId, role, timestamp, event) => {
                if (vid.toString() === voterId.toString()) {
                    console.log('[MetaMask] VoteCast event received:', {
                        transactionHash: event.log.transactionHash,
                        blockNumber: event.log.blockNumber,
                        role, voterName,
                    });
                }
            });
        } catch (e) {
            console.warn('Event watch failed:', e);
        }
    }

    // ── Bind button events ────────────────────────────────────────────

    function bindEvents() {
        document.getElementById('mm-connect-btn')
            ?.addEventListener('click', connectMetaMask);
        document.getElementById('mm-sign-btn')
            ?.addEventListener('click', signAttestation);
    }

    // ── Auto-detect MetaMask and render widget ────────────────────────

    function init() {
        if (typeof ethers === 'undefined') {
            // ethers.js not loaded yet — wait for it
            console.warn('[MetaMask] ethers.js not found. Load it before metamask.js');
            return;
        }
        injectWidget();

        // If MetaMask is not installed, show install prompt instead
        if (!window.ethereum) {
            const btn = document.getElementById('mm-connect-btn');
            if (btn) {
                btn.textContent = '📥 Install MetaMask';
                btn.onclick = () => window.open('https://metamask.io/download/', '_blank');
            }
        }
    }

    // Run after DOM ready
    if (document.readyState === 'loading') {
        document.addEventListener('DOMContentLoaded', init);
    } else {
        init();
    }

})();
